version: '3.4'

services:
  tgr.places.api:
    container_name: tgr.places.api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - docker_mongodb-net
    ports:
      - 13002:80
      
networks:
  docker_mongodb-net:
    external: true
